import { ReadingData } from './types';

export const biblePlanData: ReadingData = {
  "day_1": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Genèse 1–3", "midi_sagesse_poesie": "Psaume 1:1–6 ; Psaume 2:1–12 ; Psaume 3:1–8 ; Psaume 4:1", "soir_nouveau_testament": "Matthieu 1:1–25" },
  "day_2": { "jour_semaine": "Lundi", "matin_ancien_testament": "Genèse 4–5", "midi_sagesse_poesie": "Proverbes 1:1–11", "soir_nouveau_testament": "Matthieu 2:1–23" },
  "day_3": { "jour_semaine": "Mardi", "matin_ancien_testament": "Genèse 6–7", "midi_sagesse_poesie": "Ecclésiaste 1:1–3", "soir_nouveau_testament": "Matthieu 3:1–17" },
  "day_4": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Genèse 8–9", "midi_sagesse_poesie": "Lamentations 1:1–2", "soir_nouveau_testament": "Matthieu 4:1–25" },
  "day_5": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Genèse 10–11", "midi_sagesse_poesie": "Psaume 4:2–8 ; Psaume 5:1–12 ; Psaume 6:1–8", "soir_nouveau_testament": "Matthieu 5:1–24" },
  "day_6": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Genèse 12–13", "midi_sagesse_poesie": "Proverbes 1:12–22", "soir_nouveau_testament": "Matthieu 5:25–48" },
  "day_7": { "jour_semaine": "Samedi", "matin_ancien_testament": "Genèse 14–15", "midi_sagesse_poesie": "Ecclésiaste 1:4–6", "soir_nouveau_testament": "Matthieu 6:1–17" },
  "day_8": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Genèse 16–17", "midi_sagesse_poesie": "Lamentations 1:3–4", "soir_nouveau_testament": "Matthieu 6:18–34" },
  "day_9": { "jour_semaine": "Lundi", "matin_ancien_testament": "Genèse 18–19", "midi_sagesse_poesie": "Psaume 6:9–10 ; Psaume 7:1–17 ; Psaume 8:1–8", "soir_nouveau_testament": "Matthieu 7:1–29" },
  "day_10": { "jour_semaine": "Mardi", "matin_ancien_testament": "Genèse 20–21", "midi_sagesse_poesie": "Proverbes 1:23–33", "soir_nouveau_testament": "Matthieu 8:1–17" },
  "day_11": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Genèse 22–23", "midi_sagesse_poesie": "Ecclésiaste 1:7–9", "soir_nouveau_testament": "Matthieu 8:18–34" },
  "day_12": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Genèse 24–25", "midi_sagesse_poesie": "Lamentations 1:5–6", "soir_nouveau_testament": "Matthieu 9:1–19" },
  "day_13": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Genèse 26–27", "midi_sagesse_poesie": "Psaume 8:9 ; Psaume 9:1–20 ; Psaume 10:1–6", "soir_nouveau_testament": "Matthieu 9:20–38" },
  "day_14": { "jour_semaine": "Samedi", "matin_ancien_testament": "Genèse 28–29", "midi_sagesse_poesie": "Proverbes 2:1–11", "soir_nouveau_testament": "Matthieu 10:1–21" },
  "day_15": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Genèse 30–31", "midi_sagesse_poesie": "Ecclésiaste 1:10–12", "soir_nouveau_testament": "Matthieu 10:22–42" },
  "day_16": { "jour_semaine": "Lundi", "matin_ancien_testament": "Genèse 32–33", "midi_sagesse_poesie": "Lamentations 1:7–8", "soir_nouveau_testament": "Matthieu 11:1–30" },
  "day_17": { "jour_semaine": "Mardi", "matin_ancien_testament": "Genèse 34–35", "midi_sagesse_poesie": "Psaume 10:7–18 ; Psaume 11:1–7 ; Psaume 12:1–8", "soir_nouveau_testament": "Matthieu 12:1–25" },
  "day_18": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Genèse 36–37", "midi_sagesse_poesie": "Proverbes 2:12–22", "soir_nouveau_testament": "Matthieu 12:26–50" },
  "day_19": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Genèse 38–39", "midi_sagesse_poesie": "Ecclésiaste 1:13–14", "soir_nouveau_testament": "Matthieu 13:1–29" },
  "day_20": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Genèse 40–41", "midi_sagesse_poesie": "Lamentations 1:9–10", "soir_nouveau_testament": "Matthieu 13:30–58" },
  "day_21": { "jour_semaine": "Samedi", "matin_ancien_testament": "Genèse 42–43", "midi_sagesse_poesie": "Psaume 13:1–6 ; Psaume 14:1–7 ; Psaume 15:1–5 ; Psaume 16:1–9", "soir_nouveau_testament": "Matthieu 14:1–18" },
  "day_22": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Genèse 44–45", "midi_sagesse_poesie": "Proverbes 3:1–12", "soir_nouveau_testament": "Matthieu 14:19–36" },
  "day_23": { "jour_semaine": "Lundi", "matin_ancien_testament": "Genèse 46–47", "midi_sagesse_poesie": "Ecclésiaste 1:15–16", "soir_nouveau_testament": "Matthieu 15:1–20" },
  "day_24": { "jour_semaine": "Mardi", "matin_ancien_testament": "Genèse 48–49", "midi_sagesse_poesie": "Lamentations 1:11–12", "soir_nouveau_testament": "Matthieu 15:21–39" },
  "day_25": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Genèse 50 – Exode 1", "midi_sagesse_poesie": "Psaume 16:10–11 ; Psaume 17:1–15 ; Psaume 18:1–10", "soir_nouveau_testament": "Matthieu 16:1–28" },
  "day_26": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Exode 2–3", "midi_sagesse_poesie": "Proverbes 3:13–24", "soir_nouveau_testament": "Matthieu 17:1–27" },
  "day_27": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Exode 4–5", "midi_sagesse_poesie": "Ecclésiaste 1:17–18", "soir_nouveau_testament": "Matthieu 18:1–18" },
  "day_28": { "jour_semaine": "Samedi", "matin_ancien_testament": "Exode 6–7", "midi_sagesse_poesie": "Lamentations 1:13–14", "soir_nouveau_testament": "Matthieu 18:19–35" },
  "day_29": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Exode 8–9", "midi_sagesse_poesie": "Psaume 18:11–37", "soir_nouveau_testament": "Matthieu 19:1–30" },
  "day_30": { "jour_semaine": "Lundi", "matin_ancien_testament": "Exode 10–11", "midi_sagesse_poesie": "Proverbes 3:25–35", "soir_nouveau_testament": "Matthieu 20:1–17" },
  "day_31": { "jour_semaine": "Mardi", "matin_ancien_testament": "Exode 12–13", "midi_sagesse_poesie": "Ecclésiaste 2:1–3", "soir_nouveau_testament": "Matthieu 20:18–34" },
  "day_32": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Exode 14–15", "midi_sagesse_poesie": "Lamentations 1:15–16", "soir_nouveau_testament": "Matthieu 21:1–23" },
  "day_33": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Exode 16–17", "midi_sagesse_poesie": "Psaume 18:38–50 ; Psaume 19:1–14", "soir_nouveau_testament": "Matthieu 21:24–46" },
  "day_34": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Exode 18–19", "midi_sagesse_poesie": "Proverbes 4:1–9", "soir_nouveau_testament": "Matthieu 22:1–23" },
  "day_35": { "jour_semaine": "Samedi", "matin_ancien_testament": "Exode 20–21", "midi_sagesse_poesie": "Ecclésiaste 2:4–6", "soir_nouveau_testament": "Matthieu 22:24–46" },
  "day_36": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Exode 22–23", "midi_sagesse_poesie": "Lamentations 1:17–18", "soir_nouveau_testament": "Matthieu 23:1–20" },
  "day_37": { "jour_semaine": "Lundi", "matin_ancien_testament": "Exode 24–25", "midi_sagesse_poesie": "Psaume 20:1–9 ; Psaume 21:1–13 ; Psaume 22:1–5", "soir_nouveau_testament": "Matthieu 23:21–39" },
  "day_38": { "jour_semaine": "Mardi", "matin_ancien_testament": "Exode 26–27", "midi_sagesse_poesie": "Proverbes 4:10–18", "soir_nouveau_testament": "Matthieu 24:1–26" },
  "day_39": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Exode 28–29", "midi_sagesse_poesie": "Ecclésiaste 2:7–9", "soir_nouveau_testament": "Matthieu 24:27–51" },
  "day_40": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Exode 30–31", "midi_sagesse_poesie": "Lamentations 1:19", "soir_nouveau_testament": "Matthieu 25:1–23" },
  "day_41": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Exode 32–33", "midi_sagesse_poesie": "Psaume 22:6–31 ; Psaume 23:1", "soir_nouveau_testament": "Matthieu 25:24–46" },
  "day_42": { "jour_semaine": "Samedi", "matin_ancien_testament": "Exode 34–35", "midi_sagesse_poesie": "Proverbes 4:19–27", "soir_nouveau_testament": "Matthieu 26:1–38" },
  "day_43": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Exode 36–37", "midi_sagesse_poesie": "Ecclésiaste 2:10–12", "soir_nouveau_testament": "Matthieu 26:39–75" },
  "day_44": { "jour_semaine": "Lundi", "matin_ancien_testament": "Exode 38–39", "midi_sagesse_poesie": "Lamentations 1:20", "soir_nouveau_testament": "Matthieu 27:1–33" },
  "day_45": { "jour_semaine": "Mardi", "matin_ancien_testament": "Exode 40 – Lévitique 1", "midi_sagesse_poesie": "Psaume 23:2–6 ; Psaume 24:1–10 ; Psaume 25:1–12", "soir_nouveau_testament": "Matthieu 27:34–66" },
  "day_46": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Lévitique 2–3", "midi_sagesse_poesie": "Proverbes 5:1–12", "soir_nouveau_testament": "Matthieu 28:1–20" },
  "day_47": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Lévitique 4–5", "midi_sagesse_poesie": "Ecclésiaste 2:13–14", "soir_nouveau_testament": "Marc 1:1–23" },
  "day_48": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Lévitique 6–7", "midi_sagesse_poesie": "Lamentations 1:21", "soir_nouveau_testament": "Marc 1:24–45" },
  "day_49": { "jour_semaine": "Samedi", "matin_ancien_testament": "Lévitique 8–9", "midi_sagesse_poesie": "Psaume 25:13–22 ; Psaume 26:1–12 ; Psaume 27:1–5", "soir_nouveau_testament": "Marc 2:1–28" },
  "day_50": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Lévitique 10–11", "midi_sagesse_poesie": "Proverbes 5:13–23", "soir_nouveau_testament": "Marc 3:1–18" },
  "day_51": { "jour_semaine": "Lundi", "matin_ancien_testament": "Lévitique 12–13", "midi_sagesse_poesie": "Ecclésiaste 2:15–16", "soir_nouveau_testament": "Marc 3:19–35" },
  "day_52": { "jour_semaine": "Mardi", "matin_ancien_testament": "Lévitique 14–15", "midi_sagesse_poesie": "Lamentations 1:22", "soir_nouveau_testament": "Marc 4:1–21" },
  "day_53": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Lévitique 16–17", "midi_sagesse_poesie": "Psaume 27:6–14 ; Psaume 28:1–9 ; Psaume 29:1–9", "soir_nouveau_testament": "Marc 4:22–41" },
  "day_54": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Lévitique 18–19", "midi_sagesse_poesie": "Proverbes 6:1–12", "soir_nouveau_testament": "Marc 5:1–22" },
  "day_55": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Lévitique 20–21", "midi_sagesse_poesie": "Ecclésiaste 2:17–18", "soir_nouveau_testament": "Marc 5:23–43" },
  "day_56": { "jour_semaine": "Samedi", "matin_ancien_testament": "Lévitique 22–23", "midi_sagesse_poesie": "Lamentations 2:1–2", "soir_nouveau_testament": "Marc 6:1–28" },
  "day_57": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Lévitique 24–25", "midi_sagesse_poesie": "Psaume 29:10–11 ; Psaume 30:1–12 ; Psaume 31:1–13", "soir_nouveau_testament": "Marc 6:29–56" },
  "day_58": { "jour_semaine": "Lundi", "matin_ancien_testament": "Lévitique 26–27", "midi_sagesse_poesie": "Proverbes 6:13–24", "soir_nouveau_testament": "Marc 7:1–19" },
  "day_59": { "jour_semaine": "Mardi", "matin_ancien_testament": "Nombres 1–2", "midi_sagesse_poesie": "Ecclésiaste 2:19–20", "soir_nouveau_testament": "Marc 7:20–37" },
  "day_60": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Nombres 3–4", "midi_sagesse_poesie": "Lamentations 2:3–4", "soir_nouveau_testament": "Marc 8:1–19" },
  "day_61": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Nombres 5–6", "midi_sagesse_poesie": "Psaume 31:14–24 ; Psaume 32:1–11 ; Psaume 33:1–5", "soir_nouveau_testament": "Marc 8:20–38" },
  "day_62": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Nombres 7–8", "midi_sagesse_poesie": "Proverbes 6:25–35", "soir_nouveau_testament": "Marc 9:1–25" },
  "day_63": { "jour_semaine": "Samedi", "matin_ancien_testament": "Nombres 9–10", "midi_sagesse_poesie": "Ecclésiaste 2:21–22", "soir_nouveau_testament": "Marc 9:26–50" },
  "day_64": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Nombres 11–12", "midi_sagesse_poesie": "Lamentations 2:5–6", "soir_nouveau_testament": "Marc 10:1–26" },
  "day_65": { "jour_semaine": "Lundi", "matin_ancien_testament": "Nombres 13–14", "midi_sagesse_poesie": "Psaume 33:6–22 ; Psaume 34:1–10", "soir_nouveau_testament": "Marc 10:27–52" },
  "day_66": { "jour_semaine": "Mardi", "matin_ancien_testament": "Nombres 15–16", "midi_sagesse_poesie": "Proverbes 7:1–9", "soir_nouveau_testament": "Marc 11:1–17" },
  "day_67": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Nombres 17–18", "midi_sagesse_poesie": "Ecclésiaste 2:23–24", "soir_nouveau_testament": "Marc 11:18–33" },
  "day_68": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Nombres 19–20", "midi_sagesse_poesie": "Lamentations 2:7–8", "soir_nouveau_testament": "Marc 12:1–22" },
  "day_69": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Nombres 21–22", "midi_sagesse_poesie": "Psaume 34:11–22 ; Psaume 35:1–15", "soir_nouveau_testament": "Marc 12:23–44" },
  "day_70": { "jour_semaine": "Samedi", "matin_ancien_testament": "Nombres 23–24", "midi_sagesse_poesie": "Proverbes 7:10–18", "soir_nouveau_testament": "Marc 13:1–19" },
  "day_71": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Nombres 25–26", "midi_sagesse_poesie": "Ecclésiaste 2:25–26", "soir_nouveau_testament": "Marc 13:20–37" },
  "day_72": { "jour_semaine": "Lundi", "matin_ancien_testament": "Nombres 27–28", "midi_sagesse_poesie": "Lamentations 2:9–10", "soir_nouveau_testament": "Marc 14:1–36" },
  "day_73": { "jour_semaine": "Mardi", "matin_ancien_testament": "Nombres 29–30", "midi_sagesse_poesie": "Psaume 35:16–28 ; Psaume 36:1–12 ; Psaume 37:1–2", "soir_nouveau_testament": "Marc 14:37–72" },
  "day_74": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Nombres 31–32", "midi_sagesse_poesie": "Proverbes 7:19–27", "soir_nouveau_testament": "Marc 15:1–24" },
  "day_75": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Nombres 33–34", "midi_sagesse_poesie": "Ecclésiaste 3:1–3", "soir_nouveau_testament": "Marc 15:25–47" },
  "day_76": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Nombres 35–36", "midi_sagesse_poesie": "Lamentations 2:11–12", "soir_nouveau_testament": "Marc 16:1–20" },
  "day_77": { "jour_semaine": "Samedi", "matin_ancien_testament": "Deutéronome 1–2", "midi_sagesse_poesie": "Psaume 37:3–29", "soir_nouveau_testament": "Actes 1:1–26" },
  "day_78": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Deutéronome 3–4", "midi_sagesse_poesie": "Proverbes 8:1–9", "soir_nouveau_testament": "Actes 2:1–24" },
  "day_79": { "jour_semaine": "Lundi", "matin_ancien_testament": "Deutéronome 5–6", "midi_sagesse_poesie": "Ecclésiaste 3:4–6", "soir_nouveau_testament": "Actes 2:25–47" },
  "day_80": { "jour_semaine": "Mardi", "matin_ancien_testament": "Deutéronome 7–8", "midi_sagesse_poesie": "Lamentations 2:13–14", "soir_nouveau_testament": "Actes 3:1–26" },
  "day_81": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Deutéronome 9–10", "midi_sagesse_poesie": "Psaume 37:30–40 ; Psaume 38:1–16", "soir_nouveau_testament": "Actes 4:1–19" },
  "day_82": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Deutéronome 11–12", "midi_sagesse_poesie": "Proverbes 8:10–18", "soir_nouveau_testament": "Actes 4:20–37" },
  "day_83": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Deutéronome 13–14", "midi_sagesse_poesie": "Ecclésiaste 3:7–9", "soir_nouveau_testament": "Actes 5:1–21" },
  "day_84": { "jour_semaine": "Samedi", "matin_ancien_testament": "Deutéronome 15–16", "midi_sagesse_poesie": "Lamentations 2:15–16", "soir_nouveau_testament": "Actes 5:22–42" },
  "day_85": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Deutéronome 17–18", "midi_sagesse_poesie": "Psaume 38:17–22 ; Psaume 39:1–13 ; Psaume 40:1–8", "soir_nouveau_testament": "Actes 6:1–15" },
  "day_86": { "jour_semaine": "Lundi", "matin_ancien_testament": "Deutéronome 19–20", "midi_sagesse_poesie": "Proverbes 8:19–27", "soir_nouveau_testament": "Actes 7:1–30" },
  "day_87": { "jour_semaine": "Mardi", "matin_ancien_testament": "Deutéronome 21–22", "midi_sagesse_poesie": "Ecclésiaste 3:10–12", "soir_nouveau_testament": "Actes 7:31–60" },
  "day_88": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Deutéronome 23–24", "midi_sagesse_poesie": "Lamentations 2:17–18", "soir_nouveau_testament": "Actes 8:1–20" },
  "day_89": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Deutéronome 25–26", "midi_sagesse_poesie": "Psaume 40:9–17 ; Psaume 41:1–13 ; Psaume 42:1–5", "soir_nouveau_testament": "Actes 8:21–40" },
  "day_90": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Deutéronome 27–28", "midi_sagesse_poesie": "Proverbes 8:28–36", "soir_nouveau_testament": "Actes 9:1–22" },
  "day_91": { "jour_semaine": "Samedi", "matin_ancien_testament": "Deutéronome 29–30", "midi_sagesse_poesie": "Ecclésiaste 3:13–14", "soir_nouveau_testament": "Actes 9:23–43" },
  "day_92": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Deutéronome 31–32", "midi_sagesse_poesie": "Lamentations 2:19", "soir_nouveau_testament": "Actes 10:1–24" },
  "day_93": { "jour_semaine": "Lundi", "matin_ancien_testament": "Deutéronome 33–34", "midi_sagesse_poesie": "Psaume 42:6–11 ; Psaume 43:1–5 ; Psaume 44:1–16", "soir_nouveau_testament": "Actes 10:25–48" },
  "day_94": { "jour_semaine": "Mardi", "matin_ancien_testament": "Josué 1–2", "midi_sagesse_poesie": "Proverbes 9:1–9", "soir_nouveau_testament": "Actes 11:1–30" },
  "day_95": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Josué 3–4", "midi_sagesse_poesie": "Ecclésiaste 3:15–16", "soir_nouveau_testament": "Actes 12:1–25" },
  "day_96": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Josué 5–6", "midi_sagesse_poesie": "Lamentations 2:20", "soir_nouveau_testament": "Actes 13:1–26" },
  "day_97": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Josué 7–8", "midi_sagesse_poesie": "Psaume 44:17–26 ; Psaume 45:1–17", "soir_nouveau_testament": "Actes 13:27–52" },
  "day_98": { "jour_semaine": "Samedi", "matin_ancien_testament": "Josué 9–10", "midi_sagesse_poesie": "Proverbes 9:10–18", "soir_nouveau_testament": "Actes 14:1–28" },
  "day_99": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Josué 11–12", "midi_sagesse_poesie": "Ecclésiaste 3:17–18", "soir_nouveau_testament": "Actes 15:1–21" },
  "day_100": { "jour_semaine": "Lundi", "matin_ancien_testament": "Josué 13–14", "midi_sagesse_poesie": "Lamentations 2:21", "soir_nouveau_testament": "Actes 15:22–41" },
  "day_101": { "jour_semaine": "Mardi", "matin_ancien_testament": "Josué 15–16", "midi_sagesse_poesie": "Psaume 46:1–11 ; Psaume 47:1–9 ; Psaume 48:1–7", "soir_nouveau_testament": "Actes 16:1–20" },
  "day_102": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Josué 17–18", "midi_sagesse_poesie": "Proverbes 10:1–11", "soir_nouveau_testament": "Actes 16:21–40" },
  "day_103": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Josué 19–20", "midi_sagesse_poesie": "Ecclésiaste 3:19–20", "soir_nouveau_testament": "Actes 17:1–17" },
  "day_104": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Josué 21–22", "midi_sagesse_poesie": "Lamentations 2:22", "soir_nouveau_testament": "Actes 17:18–34" },
  "day_105": { "jour_semaine": "Samedi", "matin_ancien_testament": "Josué 23–24", "midi_sagesse_poesie": "Psaume 48:8–14 ; Psaume 49:1–20", "soir_nouveau_testament": "Actes 18:1–28" },
  "day_106": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Juges 1–2", "midi_sagesse_poesie": "Proverbes 10:12–22", "soir_nouveau_testament": "Actes 19:1–20" },
  "day_107": { "jour_semaine": "Lundi", "matin_ancien_testament": "Juges 3–4", "midi_sagesse_poesie": "Ecclésiaste 3:21–22", "soir_nouveau_testament": "Actes 19:21–40" },
  "day_108": { "jour_semaine": "Mardi", "matin_ancien_testament": "Juges 5–6", "midi_sagesse_poesie": "Lamentations 3:1–2", "soir_nouveau_testament": "Actes 20:1–19" },
  "day_109": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Juges 7–8", "midi_sagesse_poesie": "Psaume 50:1–23 ; Psaume 51:1–4", "soir_nouveau_testament": "Actes 20:20–38" },
  "day_110": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Juges 9–10", "midi_sagesse_poesie": "Proverbes 10:23–32", "soir_nouveau_testament": "Actes 21:1–20" },
  "day_111": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Juges 11–12", "midi_sagesse_poesie": "Ecclésiaste 4:1–3", "soir_nouveau_testament": "Actes 21:21–40" },
  "day_112": { "jour_semaine": "Samedi", "matin_ancien_testament": "Juges 13–14", "midi_sagesse_poesie": "Lamentations 3:3–4", "soir_nouveau_testament": "Actes 22:1–30" },
  "day_113": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Juges 15–16", "midi_sagesse_poesie": "Psaume 51:5–19 ; Psaume 52:1–9 ; Psaume 53:1–3", "soir_nouveau_testament": "Actes 23:1–18" },
  "day_114": { "jour_semaine": "Lundi", "matin_ancien_testament": "Juges 17–18", "midi_sagesse_poesie": "Proverbes 11:1–11", "soir_nouveau_testament": "Actes 23:19–35" },
  "day_115": { "jour_semaine": "Mardi", "matin_ancien_testament": "Juges 19–20", "midi_sagesse_poesie": "Ecclésiaste 4:4–6", "soir_nouveau_testament": "Actes 24:1–27" },
  "day_116": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Juges 21 – Ruth 1", "midi_sagesse_poesie": "Lamentations 3:5–6", "soir_nouveau_testament": "Actes 25:1–27" },
  "day_117": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ruth 2–3", "midi_sagesse_poesie": "Psaume 53:4–6 ; Psaume 54:1–7 ; Psaume 55:1–17", "soir_nouveau_testament": "Actes 26:1–16" },
  "day_118": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ruth 4 – 1 Samuel 1", "midi_sagesse_poesie": "Proverbes 11:12–21", "soir_nouveau_testament": "Actes 26:17–32" },
  "day_119": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Samuel 2–3", "midi_sagesse_poesie": "Ecclésiaste 4:7–8", "soir_nouveau_testament": "Actes 27:1–22" },
  "day_120": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Samuel 4–5", "midi_sagesse_poesie": "Lamentations 3:7–8", "soir_nouveau_testament": "Actes 27:23–44" },
  "day_121": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Samuel 6–7", "midi_sagesse_poesie": "Psaume 55:18–23 ; Psaume 56:1–13 ; Psaume 57:1–8", "soir_nouveau_testament": "Actes 28:1–16" },
  "day_122": { "jour_semaine": "Mardi", "matin_ancien_testament": "1 Samuel 8–9", "midi_sagesse_poesie": "Proverbes 11:22–31", "soir_nouveau_testament": "Actes 28:17–31" },
  "day_123": { "jour_semaine": "Mercredi", "matin_ancien_testament": "1 Samuel 10–11", "midi_sagesse_poesie": "Ecclésiaste 4:9–10", "soir_nouveau_testament": "Romains 1:1–16" },
  "day_124": { "jour_semaine": "Jeudi", "matin_ancien_testament": "1 Samuel 12–13", "midi_sagesse_poesie": "Lamentations 3:9–10", "soir_nouveau_testament": "Romains 1:17–32" },
  "day_125": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Samuel 14–15", "midi_sagesse_poesie": "Psaume 57:9–11 ; Psaume 58:1–11 ; Psaume 59:1–13", "soir_nouveau_testament": "Romains 2:1–29" },
  "day_126": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Samuel 16–17", "midi_sagesse_poesie": "Proverbes 12:1–10", "soir_nouveau_testament": "Romains 3:1–16" },
  "day_127": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Samuel 18–19", "midi_sagesse_poesie": "Ecclésiaste 4:11–12", "soir_nouveau_testament": "Romains 3:17–31" },
  "day_128": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Samuel 20–21", "midi_sagesse_poesie": "Lamentations 3:11–12", "soir_nouveau_testament": "Romains 4:1–25" },
  "day_129": { "jour_semaine": "Mardi", "matin_ancien_testament": "1 Samuel 22–23", "midi_sagesse_poesie": "Psaume 59:14–17 ; Psaume 60:1–12 ; Psaume 61:1–8 ; Psaume 62:1–3", "soir_nouveau_testament": "Romains 5:1–21" },
  "day_130": { "jour_semaine": "Mercredi", "matin_ancien_testament": "1 Samuel 24–25", "midi_sagesse_poesie": "Proverbes 12:11–19", "soir_nouveau_testament": "Romains 6:1–23" },
  "day_131": { "jour_semaine": "Jeudi", "matin_ancien_testament": "1 Samuel 26–27", "midi_sagesse_poesie": "Ecclésiaste 4:13–14", "soir_nouveau_testament": "Romains 7:1–25" },
  "day_132": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Samuel 28–29", "midi_sagesse_poesie": "Lamentations 3:13–14", "soir_nouveau_testament": "Romains 8:1–20" },
  "day_133": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Samuel 30–31", "midi_sagesse_poesie": "Psaume 62:4–12 ; Psaume 63:1–11 ; Psaume 64:1–7", "soir_nouveau_testament": "Romains 8:21–39" },
  "day_134": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Samuel 1–2", "midi_sagesse_poesie": "Proverbes 12:20–28", "soir_nouveau_testament": "Romains 9:1–17" },
  "day_135": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Samuel 3–4", "midi_sagesse_poesie": "Ecclésiaste 4:15–16", "soir_nouveau_testament": "Romains 9:18–33" },
  "day_136": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Samuel 5–6", "midi_sagesse_poesie": "Lamentations 3:15–16", "soir_nouveau_testament": "Romains 10:1–21" },
  "day_137": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Samuel 7–8", "midi_sagesse_poesie": "Psaume 64:8–10 ; Psaume 65:1–13 ; Psaume 66:1–11", "soir_nouveau_testament": "Romains 11:1–18" },
  "day_138": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Samuel 9–10", "midi_sagesse_poesie": "Proverbes 13:1–9", "soir_nouveau_testament": "Romains 11:19–36" },
  "day_139": { "jour_semaine": "Vendredi", "matin_ancien_testament": "2 Samuel 11–12", "midi_sagesse_poesie": "Ecclésiaste 5:1–3", "soir_nouveau_testament": "Romains 12:1–21" },
  "day_140": { "jour_semaine": "Samedi", "matin_ancien_testament": "2 Samuel 13–14", "midi_sagesse_poesie": "Lamentations 3:17–18", "soir_nouveau_testament": "Romains 13:1–14" },
  "day_141": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Samuel 15–16", "midi_sagesse_poesie": "Psaume 66:12–20 ; Psaume 67:1–7 ; Psaume 68:1–11", "soir_nouveau_testament": "Romains 14:1–23" },
  "day_142": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Samuel 17–18", "midi_sagesse_poesie": "Proverbes 13:10–17", "soir_nouveau_testament": "Romains 15:1–17" },
  "day_143": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Samuel 19–20", "midi_sagesse_poesie": "Ecclésiaste 5:4–6", "soir_nouveau_testament": "Romains 15:18–33" },
  "day_144": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Samuel 21–22", "midi_sagesse_poesie": "Lamentations 3:19–20", "soir_nouveau_testament": "Romains 16:1–27" },
  "day_145": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Samuel 23–24", "midi_sagesse_poesie": "Psaume 68:12–35 ; Psaume 69:1–3", "soir_nouveau_testament": "Luc 1:1–40" },
  "day_146": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Rois 1–2", "midi_sagesse_poesie": "Proverbes 13:18–25", "soir_nouveau_testament": "Luc 1:41–80" },
  "day_147": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Rois 3–4", "midi_sagesse_poesie": "Ecclésiaste 5:7–9", "soir_nouveau_testament": "Luc 2:1–26" },
  "day_148": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Rois 5–6", "midi_sagesse_poesie": "Lamentations 3:21–22", "soir_nouveau_testament": "Luc 2:27–52" },
  "day_149": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Rois 7–8", "midi_sagesse_poesie": "Psaume 69:4–30", "soir_nouveau_testament": "Luc 3:1–19" },
  "day_150": { "jour_semaine": "Mardi", "matin_ancien_testament": "1 Rois 9–10", "midi_sagesse_poesie": "Proverbes 14:1–12", "soir_nouveau_testament": "Luc 3:20–38" },
  "day_151": { "jour_semaine": "Mercredi", "matin_ancien_testament": "1 Rois 11–12", "midi_sagesse_poesie": "Ecclésiaste 5:10–12", "soir_nouveau_testament": "Luc 4:1–22" },
  "day_152": { "jour_semaine": "Jeudi", "matin_ancien_testament": "1 Rois 13–14", "midi_sagesse_poesie": "Lamentations 3:23–24", "soir_nouveau_testament": "Luc 4:23–44" },
  "day_153": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Rois 15–16", "midi_sagesse_poesie": "Psaume 69:31–35 ; Psaume 70:1–5 ; Psaume 71:1–17", "soir_nouveau_testament": "Luc 5:1–20" },
  "day_154": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Rois 17–18", "midi_sagesse_poesie": "Proverbes 14:13–24", "soir_nouveau_testament": "Luc 5:21–39" },
  "day_155": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Rois 19–20", "midi_sagesse_poesie": "Ecclésiaste 5:13–14", "soir_nouveau_testament": "Luc 6:1–25" },
  "day_156": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Rois 21–22", "midi_sagesse_poesie": "Lamentations 3:25–26", "soir_nouveau_testament": "Luc 6:26–49" },
  "day_157": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Rois 1–2", "midi_sagesse_poesie": "Psaume 71:18–24 ; Psaume 72:1–20", "soir_nouveau_testament": "Luc 7:1–25" },
  "day_158": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Rois 3–4", "midi_sagesse_poesie": "Proverbes 14:25–35", "soir_nouveau_testament": "Luc 7:26–50" },
  "day_159": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Rois 5–6", "midi_sagesse_poesie": "Ecclésiaste 5:15–16", "soir_nouveau_testament": "Luc 8:1–28" },
  "day_160": { "jour_semaine": "Vendredi", "matin_ancien_testament": "2 Rois 7–8", "midi_sagesse_poesie": "Lamentations 3:27–28", "soir_nouveau_testament": "Luc 8:29–56" },
  "day_161": { "jour_semaine": "Samedi", "matin_ancien_testament": "2 Rois 9–10", "midi_sagesse_poesie": "Psaume 73:1–27", "soir_nouveau_testament": "Luc 9:1–31" },
  "day_162": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Rois 11–12", "midi_sagesse_poesie": "Proverbes 15:1–11", "soir_nouveau_testament": "Luc 9:32–62" },
  "day_163": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Rois 13–14", "midi_sagesse_poesie": "Ecclésiaste 5:17–18", "soir_nouveau_testament": "Luc 10:1–21" },
  "day_164": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Rois 15–16", "midi_sagesse_poesie": "Lamentations 3:29–30", "soir_nouveau_testament": "Luc 10:22–42" },
  "day_165": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Rois 17–18", "midi_sagesse_poesie": "Psaume 73:28 ; Psaume 74:1–23 ; Psaume 75:1–3", "soir_nouveau_testament": "Luc 11:1–27" },
  "day_166": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Rois 19–20", "midi_sagesse_poesie": "Proverbes 15:12–22", "soir_nouveau_testament": "Luc 11:28–54" },
  "day_167": { "jour_semaine": "Vendredi", "matin_ancien_testament": "2 Rois 21–22", "midi_sagesse_poesie": "Ecclésiaste 5:19–20", "soir_nouveau_testament": "Luc 12:1–30" },
  "day_168": { "jour_semaine": "Samedi", "matin_ancien_testament": "2 Rois 23–24", "midi_sagesse_poesie": "Lamentations 3:31–32", "soir_nouveau_testament": "Luc 12:31–59" },
  "day_169": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Rois 25 – 1 Chroniques 1", "midi_sagesse_poesie": "Psaume 75:4–10 ; Psaume 76:1–12 ; Psaume 77:1–8", "soir_nouveau_testament": "Luc 13:1–18" },
  "day_170": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Chroniques 2–3", "midi_sagesse_poesie": "Proverbes 15:23–33", "soir_nouveau_testament": "Luc 13:19–35" },
  "day_171": { "jour_semaine": "Mardi", "matin_ancien_testament": "1 Chroniques 4–5", "midi_sagesse_poesie": "Ecclésiaste 6:1–3", "soir_nouveau_testament": "Luc 14:1–18" },
  "day_172": { "jour_semaine": "Mercredi", "matin_ancien_testament": "1 Chroniques 6–7", "midi_sagesse_poesie": "Lamentations 3:33–34", "soir_nouveau_testament": "Luc 14:19–35" },
  "day_173": { "jour_semaine": "Jeudi", "matin_ancien_testament": "1 Chroniques 8–9", "midi_sagesse_poesie": "Psaume 77:9–20 ; Psaume 78:1–15", "soir_nouveau_testament": "Luc 15:1–16" },
  "day_174": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Chroniques 10–11", "midi_sagesse_poesie": "Proverbes 16:1–11", "soir_nouveau_testament": "Luc 15:17–32" },
  "day_175": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Chroniques 12–13", "midi_sagesse_poesie": "Ecclésiaste 6:4–6", "soir_nouveau_testament": "Luc 16:1–16" },
  "day_176": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Chroniques 14–15", "midi_sagesse_poesie": "Lamentations 3:35–36", "soir_nouveau_testament": "Luc 16:17–31" },
  "day_177": { "jour_semaine": "Lundi", "matin_ancien_testament": "1 Chroniques 16–17", "midi_sagesse_poesie": "Psaume 78:16–42", "soir_nouveau_testament": "Luc 17:1–19" },
  "day_178": { "jour_semaine": "Mardi", "matin_ancien_testament": "1 Chroniques 18–19", "midi_sagesse_poesie": "Proverbes 16:12–22", "soir_nouveau_testament": "Luc 17:20–37" },
  "day_179": { "jour_semaine": "Mercredi", "matin_ancien_testament": "1 Chroniques 20–21", "midi_sagesse_poesie": "Ecclésiaste 6:7–8", "soir_nouveau_testament": "Luc 18:1–22" },
  "day_180": { "jour_semaine": "Jeudi", "matin_ancien_testament": "1 Chroniques 22–23", "midi_sagesse_poesie": "Lamentations 3:37–38", "soir_nouveau_testament": "Luc 18:23–43" },
  "day_181": { "jour_semaine": "Vendredi", "matin_ancien_testament": "1 Chroniques 24–25", "midi_sagesse_poesie": "Psaume 78:43–69", "soir_nouveau_testament": "Luc 19:1–24" },
  "day_182": { "jour_semaine": "Samedi", "matin_ancien_testament": "1 Chroniques 26–27", "midi_sagesse_poesie": "Proverbes 16:23–33", "soir_nouveau_testament": "Luc 19:25–48" },
  "day_183": { "jour_semaine": "Dimanche", "matin_ancien_testament": "1 Chroniques 28–29", "midi_sagesse_poesie": "Ecclésiaste 6:9–10", "soir_nouveau_testament": "Luc 20:1–24" },
  "day_184": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Chroniques 1–2", "midi_sagesse_poesie": "Lamentations 3:39–40", "soir_nouveau_testament": "Luc 20:25–47" },
  "day_185": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Chroniques 3–4", "midi_sagesse_poesie": "Psaume 78:70–72 ; Psaume 79:1–13 ; Psaume 80:1–11", "soir_nouveau_testament": "Luc 21:1–19" },
  "day_186": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Chroniques 5–6", "midi_sagesse_poesie": "Proverbes 17:1–10", "soir_nouveau_testament": "Luc 21:20–38" },
  "day_187": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Chroniques 7–8", "midi_sagesse_poesie": "Ecclésiaste 6:11–12", "soir_nouveau_testament": "Luc 22:1–36" },
  "day_188": { "jour_semaine": "Vendredi", "matin_ancien_testament": "2 Chroniques 9–10", "midi_sagesse_poesie": "Lamentations 3:41–42", "soir_nouveau_testament": "Luc 22:37–71" },
  "day_189": { "jour_semaine": "Samedi", "matin_ancien_testament": "2 Chroniques 11–12", "midi_sagesse_poesie": "Psaume 80:12–19 ; Psaume 81:1–16 ; Psaume 82:1–3", "soir_nouveau_testament": "Luc 23:1–28" },
  "day_190": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Chroniques 13–14", "midi_sagesse_poesie": "Proverbes 17:11–19", "soir_nouveau_testament": "Luc 23:29–56" },
  "day_191": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Chroniques 15–16", "midi_sagesse_poesie": "Ecclésiaste 7:1–3", "soir_nouveau_testament": "Luc 24:1–27" },
  "day_192": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Chroniques 17–18", "midi_sagesse_poesie": "Lamentations 3:43–44", "soir_nouveau_testament": "Luc 24:28–53" },
  "day_193": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Chroniques 19–20", "midi_sagesse_poesie": "Psaume 82:4–8 ; Psaume 83:1–18 ; Psaume 84:1–4", "soir_nouveau_testament": "Jean 1:1–26" },
  "day_194": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Chroniques 21–22", "midi_sagesse_poesie": "Proverbes 17:20–28", "soir_nouveau_testament": "Jean 1:27–51" },
  "day_195": { "jour_semaine": "Vendredi", "matin_ancien_testament": "2 Chroniques 23–24", "midi_sagesse_poesie": "Ecclésiaste 7:4–6", "soir_nouveau_testament": "Jean 2:1–25" },
  "day_196": { "jour_semaine": "Samedi", "matin_ancien_testament": "2 Chroniques 25–26", "midi_sagesse_poesie": "Lamentations 3:45–46", "soir_nouveau_testament": "Jean 3:1–18" },
  "day_197": { "jour_semaine": "Dimanche", "matin_ancien_testament": "2 Chroniques 27–28", "midi_sagesse_poesie": "Psaume 84:5–12 ; Psaume 85:1–13 ; Psaume 86:1–6", "soir_nouveau_testament": "Jean 3:19–36" },
  "day_198": { "jour_semaine": "Lundi", "matin_ancien_testament": "2 Chroniques 29–30", "midi_sagesse_poesie": "Proverbes 18:1–8", "soir_nouveau_testament": "Jean 4:1–27" },
  "day_199": { "jour_semaine": "Mardi", "matin_ancien_testament": "2 Chroniques 31–32", "midi_sagesse_poesie": "Ecclésiaste 7:7–9", "soir_nouveau_testament": "Jean 4:28–54" },
  "day_200": { "jour_semaine": "Mercredi", "matin_ancien_testament": "2 Chroniques 33–34", "midi_sagesse_poesie": "Lamentations 3:47–48", "soir_nouveau_testament": "Jean 5:1–24" },
  "day_201": { "jour_semaine": "Jeudi", "matin_ancien_testament": "2 Chroniques 35–36", "midi_sagesse_poesie": "Psaume 86:7–17 ; Psaume 87:1–7 ; Psaume 88:1–9", "soir_nouveau_testament": "Jean 5:25–47" },
  "day_202": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Esdras 1–2", "midi_sagesse_poesie": "Proverbes 18:9–16", "soir_nouveau_testament": "Jean 6:1–36" },
  "day_203": { "jour_semaine": "Samedi", "matin_ancien_testament": "Esdras 3–4", "midi_sagesse_poesie": "Ecclésiaste 7:10–12", "soir_nouveau_testament": "Jean 6:37–71" },
  "day_204": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Esdras 5–6", "midi_sagesse_poesie": "Lamentations 3:49–50", "soir_nouveau_testament": "Jean 7:1–27" },
  "day_205": { "jour_semaine": "Lundi", "matin_ancien_testament": "Esdras 7–8", "midi_sagesse_poesie": "Psaume 88:10–18 ; Psaume 89:1–18", "soir_nouveau_testament": "Jean 7:28–53" },
  "day_206": { "jour_semaine": "Mardi", "matin_ancien_testament": "Esdras 9–10", "midi_sagesse_poesie": "Proverbes 18:17–24", "soir_nouveau_testament": "Jean 8:1–30" },
  "day_207": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Néhémie 1–2", "midi_sagesse_poesie": "Ecclésiaste 7:13–15", "soir_nouveau_testament": "Jean 8:31–59" },
  "day_208": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Néhémie 3–4", "midi_sagesse_poesie": "Lamentations 3:51–52", "soir_nouveau_testament": "Jean 9:1–21" },
  "day_209": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Néhémie 5–6", "midi_sagesse_poesie": "Psaume 89:19–45", "soir_nouveau_testament": "Jean 9:22–41" },
  "day_210": { "jour_semaine": "Samedi", "matin_ancien_testament": "Néhémie 7–8", "midi_sagesse_poesie": "Proverbes 19:1–10", "soir_nouveau_testament": "Jean 10:1–21" },
  "day_211": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Néhémie 9–10", "midi_sagesse_poesie": "Ecclésiaste 7:16–17", "soir_nouveau_testament": "Jean 10:22–42" },
  "day_212": { "jour_semaine": "Lundi", "matin_ancien_testament": "Néhémie 11–12", "midi_sagesse_poesie": "Lamentations 3:53–54", "soir_nouveau_testament": "Jean 11:1–29" },
  "day_213": { "jour_semaine": "Mardi", "matin_ancien_testament": "Néhémie 13 – Esther 1", "midi_sagesse_poesie": "Psaume 89:46–52 ; Psaume 90:1–17 ; Psaume 91:1–3", "soir_nouveau_testament": "Jean 11:30–57" },
  "day_214": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Esther 2–3", "midi_sagesse_poesie": "Proverbes 19:11–20", "soir_nouveau_testament": "Jean 12:1–25" },
  "day_215": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Esther 4–5", "midi_sagesse_poesie": "Ecclésiaste 7:18–19", "soir_nouveau_testament": "Jean 12:26–50" },
  "day_216": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Esther 6–7", "midi_sagesse_poesie": "Lamentations 3:55", "soir_nouveau_testament": "Jean 13:1–19" },
  "day_217": { "jour_semaine": "Samedi", "matin_ancien_testament": "Esther 8–9", "midi_sagesse_poesie": "Psaume 91:4–16 ; Psaume 92:1–14", "soir_nouveau_testament": "Jean 13:20–38" },
  "day_218": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Esther 10 – Job 1", "midi_sagesse_poesie": "Proverbes 19:21–29", "soir_nouveau_testament": "Jean 14:1–31" },
  "day_219": { "jour_semaine": "Lundi", "matin_ancien_testament": "Job 2–3", "midi_sagesse_poesie": "Ecclésiaste 7:20–21", "soir_nouveau_testament": "Jean 15:1–27" },
  "day_220": { "jour_semaine": "Mardi", "matin_ancien_testament": "Job 4–5", "midi_sagesse_poesie": "Lamentations 3:56", "soir_nouveau_testament": "Jean 16:1–17" },
  "day_221": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Job 6–7", "midi_sagesse_poesie": "Psaume 92:15 ; Psaume 93:1–5 ; Psaume 94:1–21", "soir_nouveau_testament": "Jean 16:18–33" },
  "day_222": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Job 8–9", "midi_sagesse_poesie": "Proverbes 20:1–10", "soir_nouveau_testament": "Jean 17:1–26" },
  "day_223": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Job 10–11", "midi_sagesse_poesie": "Ecclésiaste 7:22–23", "soir_nouveau_testament": "Jean 18:1–20" },
  "day_224": { "jour_semaine": "Samedi", "matin_ancien_testament": "Job 12–13", "midi_sagesse_poesie": "Lamentations 3:57", "soir_nouveau_testament": "Jean 18:21–40" },
  "day_225": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Job 14–15", "midi_sagesse_poesie": "Psaume 94:22–23 ; Psaume 95:1–11 ; Psaume 96:1–13 ; Psaume 97:1", "soir_nouveau_testament": "Jean 19:1–21" },
  "day_226": { "jour_semaine": "Lundi", "matin_ancien_testament": "Job 16–17", "midi_sagesse_poesie": "Proverbes 20:11–20", "soir_nouveau_testament": "Jean 19:22–42" },
  "day_227": { "jour_semaine": "Mardi", "matin_ancien_testament": "Job 18–19", "midi_sagesse_poesie": "Ecclésiaste 7:24–25", "soir_nouveau_testament": "Jean 20:1–31" },
  "day_228": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Job 20–21", "midi_sagesse_poesie": "Lamentations 3:58", "soir_nouveau_testament": "Jean 21:1–25" },
  "day_229": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Job 22–23", "midi_sagesse_poesie": "Psaume 97:2–12 ; Psaume 98:1–9 ; Psaume 99:1–7", "soir_nouveau_testament": "1Corinthiens 1:1–31" },
  "day_230": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Job 24–25", "midi_sagesse_poesie": "Proverbes 20:21–30", "soir_nouveau_testament": "1Corinthiens 2:1–16" },
  "day_231": { "jour_semaine": "Samedi", "matin_ancien_testament": "Job 26–27", "midi_sagesse_poesie": "Ecclésiaste 7:26–27", "soir_nouveau_testament": "1Corinthiens 3:1–23" },
  "day_232": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Job 28–29", "midi_sagesse_poesie": "Lamentations 3:59", "soir_nouveau_testament": "1Corinthiens 4:1–21" },
  "day_233": { "jour_semaine": "Lundi", "matin_ancien_testament": "Job 30–31", "midi_sagesse_poesie": "Psaume 99:8–9 ; Psaume 100:1–5 ; Psaume 101:1–8 ; Psaume 102:1–12", "soir_nouveau_testament": "1Corinthiens 5:1–13" },
  "day_234": { "jour_semaine": "Mardi", "matin_ancien_testament": "Job 32–33", "midi_sagesse_poesie": "Proverbes 21:1–11", "soir_nouveau_testament": "1Corinthiens 6:1–20" },
  "day_235": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Job 34–35", "midi_sagesse_poesie": "Ecclésiaste 7:28–29", "soir_nouveau_testament": "1Corinthiens 7:1–20" },
  "day_236": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Job 36–37", "midi_sagesse_poesie": "Lamentations 3:60", "soir_nouveau_testament": "1Corinthiens 7:21–40" },
  "day_237": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Job 38–39", "midi_sagesse_poesie": "Psaume 102:13–28 ; Psaume 103:1–11", "soir_nouveau_testament": "1Corinthiens 8:1–13" },
  "day_238": { "jour_semaine": "Samedi", "matin_ancien_testament": "Job 40–41", "midi_sagesse_poesie": "Proverbes 21:12–21", "soir_nouveau_testament": "1Corinthiens 9:1–27" },
  "day_239": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Job 42 – Cantique des Cantiques 1", "midi_sagesse_poesie": "Ecclésiaste 8:1–3", "soir_nouveau_testament": "1Corinthiens 10:1–17" },
  "day_240": { "jour_semaine": "Lundi", "matin_ancien_testament": "Cantique des Cantiques 2–3", "midi_sagesse_poesie": "Lamentations 3:61", "soir_nouveau_testament": "1Corinthiens 10:18–33" },
  "day_241": { "jour_semaine": "Mardi", "matin_ancien_testament": "Cantique des Cantiques 4–5", "midi_sagesse_poesie": "Psaume 103:12–22 ; Psaume 104:1–16", "soir_nouveau_testament": "1Corinthiens 11:1–17" },
  "day_242": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Cantique des Cantiques 6–7", "midi_sagesse_poesie": "Proverbes 21:22–31", "soir_nouveau_testament": "1Corinthiens 11:18–34" },
  "day_243": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Cantique des Cantiques 8 – Ésaïe 1", "midi_sagesse_poesie": "Ecclésiaste 8:4–6", "soir_nouveau_testament": "1Corinthiens 12:1–31" },
  "day_244": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ésaïe 2–3", "midi_sagesse_poesie": "Lamentations 3:62", "soir_nouveau_testament": "1Corinthiens 13:1–13" },
  "day_245": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ésaïe 4–5", "midi_sagesse_poesie": "Psaume 104:17–35 ; Psaume 105:1–8", "soir_nouveau_testament": "1Corinthiens 14:1–20" },
  "day_246": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ésaïe 6–7", "midi_sagesse_poesie": "Proverbes 22:1–10", "soir_nouveau_testament": "1Corinthiens 14:21–40" },
  "day_247": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ésaïe 8–9", "midi_sagesse_poesie": "Ecclésiaste 8:7–9", "soir_nouveau_testament": "1Corinthiens 15:1–29" },
  "day_248": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ésaïe 10–11", "midi_sagesse_poesie": "Lamentations 3:63", "soir_nouveau_testament": "1Corinthiens 15:30–58" },
  "day_249": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ésaïe 12–13", "midi_sagesse_poesie": "Psaume 105:9–35", "soir_nouveau_testament": "1Corinthiens 16:1–24" },
  "day_250": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ésaïe 14–15", "midi_sagesse_poesie": "Proverbes 22:11–20", "soir_nouveau_testament": "2Corinthiens 1:1–24" },
  "day_251": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ésaïe 16–17", "midi_sagesse_poesie": "Ecclésiaste 8:10–11", "soir_nouveau_testament": "2Corinthiens 2:1–17" },
  "day_252": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ésaïe 18–19", "midi_sagesse_poesie": "Lamentations 3:64", "soir_nouveau_testament": "2Corinthiens 3:1–18" },
  "day_253": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ésaïe 20–21", "midi_sagesse_poesie": "Psaume 105:36–45 ; Psaume 106:1–17", "soir_nouveau_testament": "2Corinthiens 4:1–18" },
  "day_254": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ésaïe 22–23", "midi_sagesse_poesie": "Proverbes 22:21–29", "soir_nouveau_testament": "2Corinthiens 5:1–21" },
  "day_255": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ésaïe 24–25", "midi_sagesse_poesie": "Ecclésiaste 8:12–13", "soir_nouveau_testament": "2Corinthiens 6:1–18" },
  "day_256": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ésaïe 26–27", "midi_sagesse_poesie": "Lamentations 3:65", "soir_nouveau_testament": "2Corinthiens 7:1–16" },
  "day_257": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ésaïe 28–29", "midi_sagesse_poesie": "Psaume 106:18–44", "soir_nouveau_testament": "2Corinthiens 8:1–24" },
  "day_258": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ésaïe 30–31", "midi_sagesse_poesie": "Proverbes 23:1–12", "soir_nouveau_testament": "2Corinthiens 9:1–15" },
  "day_259": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ésaïe 32–33", "midi_sagesse_poesie": "Ecclésiaste 8:14–15", "soir_nouveau_testament": "2Corinthiens 10:1–18" },
  "day_260": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ésaïe 34–35", "midi_sagesse_poesie": "Lamentations 3:66", "soir_nouveau_testament": "2Corinthiens 11:1–17" },
  "day_261": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ésaïe 36–37", "midi_sagesse_poesie": "Psaume 106:45–48 ; Psaume 107:1–23", "soir_nouveau_testament": "2Corinthiens 11:18–33" },
  "day_262": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ésaïe 38–39", "midi_sagesse_poesie": "Proverbes 23:13–24", "soir_nouveau_testament": "2Corinthiens 12:1–21" },
  "day_263": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ésaïe 40–41", "midi_sagesse_poesie": "Ecclésiaste 8:16–17", "soir_nouveau_testament": "2Corinthiens 13:1–13" },
  "day_264": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ésaïe 42–43", "midi_sagesse_poesie": "Lamentations 4:1–2", "soir_nouveau_testament": "Ephesiens 1:1–23" },
  "day_265": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ésaïe 44–45", "midi_sagesse_poesie": "Psaume 107:24–43 ; Psaume 108:1–7", "soir_nouveau_testament": "Ephesiens 2:1–22" },
  "day_266": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ésaïe 46–47", "midi_sagesse_poesie": "Proverbes 23:25–35", "soir_nouveau_testament": "Ephesiens 3:1–21" },
  "day_267": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ésaïe 48–49", "midi_sagesse_poesie": "Ecclésiaste 9:1–3", "soir_nouveau_testament": "Ephesiens 4:1–16" },
  "day_268": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ésaïe 50–51", "midi_sagesse_poesie": "Lamentations 4:3–4", "soir_nouveau_testament": "Ephesiens 4:17–32" },
  "day_269": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ésaïe 52–53", "midi_sagesse_poesie": "Psaume 108:8–13 ; Psaume 109:1–21", "soir_nouveau_testament": "Ephesiens 5:1–17" },
  "day_270": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ésaïe 54–55", "midi_sagesse_poesie": "Proverbes 24:1–12", "soir_nouveau_testament": "Ephesiens 5:18–33" },
  "day_271": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ésaïe 56–57", "midi_sagesse_poesie": "Ecclésiaste 9:4–6", "soir_nouveau_testament": "Ephesiens 6:1–24" },
  "day_272": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ésaïe 58–59", "midi_sagesse_poesie": "Lamentations 4:5–6", "soir_nouveau_testament": "Philippiens 1:1–30" },
  "day_273": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ésaïe 60–61", "midi_sagesse_poesie": "Psaume 109:22–31 ; Psaume 110:1–7 ; Psaume 111:1–10", "soir_nouveau_testament": "Philippiens 2:1–30" },
  "day_274": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ésaïe 62–63", "midi_sagesse_poesie": "Proverbes 24:13–23", "soir_nouveau_testament": "Philippiens 3:1–21" },
  "day_275": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ésaïe 64–65", "midi_sagesse_poesie": "Ecclésiaste 9:7–9", "soir_nouveau_testament": "Philippiens 4:1–23" },
  "day_276": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ésaïe 66 – Jérémie 1", "midi_sagesse_poesie": "Lamentations 4:7–8", "soir_nouveau_testament": "Colossiens 1:1–29" },
  "day_277": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Jérémie 2–3", "midi_sagesse_poesie": "Psaume 112:1–10 ; Psaume 113:1–9 ; Psaume 114:1–8", "soir_nouveau_testament": "Colossiens 2:1–23" },
  "day_278": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Jérémie 4–5", "midi_sagesse_poesie": "Proverbes 24:24–34", "soir_nouveau_testament": "Colossiens 3:1–25" },
  "day_279": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Jérémie 6–7", "midi_sagesse_poesie": "Ecclésiaste 9:10–12", "soir_nouveau_testament": "Colossiens 4:1–18" },
  "day_280": { "jour_semaine": "Samedi", "matin_ancien_testament": "Jérémie 8–9", "midi_sagesse_poesie": "Lamentations 4:9–10", "soir_nouveau_testament": "Galates 1:1–24" },
  "day_281": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Jérémie 10–11", "midi_sagesse_poesie": "Psaume 115:1–18 ; Psaume 116:1–9", "soir_nouveau_testament": "Galates 2:1–21" },
  "day_282": { "jour_semaine": "Lundi", "matin_ancien_testament": "Jérémie 12–13", "midi_sagesse_poesie": "Proverbes 25:1–10", "soir_nouveau_testament": "Galates 3:1–29" },
  "day_283": { "jour_semaine": "Mardi", "matin_ancien_testament": "Jérémie 14–15", "midi_sagesse_poesie": "Ecclésiaste 9:13–14", "soir_nouveau_testament": "Galates 4:1–31" },
  "day_284": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Jérémie 16–17", "midi_sagesse_poesie": "Lamentations 4:11–12", "soir_nouveau_testament": "Galates 5:1–26" },
  "day_285": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Jérémie 18–19", "midi_sagesse_poesie": "Psaume 116:10–19 ; Psaume 117:1–2 ; Psaume 118:1–15", "soir_nouveau_testament": "Galates 6:1–18" },
  "day_286": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Jérémie 20–21", "midi_sagesse_poesie": "Proverbes 25:11–19", "soir_nouveau_testament": "Hebreux 1:1–14" },
  "day_287": { "jour_semaine": "Samedi", "matin_ancien_testament": "Jérémie 22–23", "midi_sagesse_poesie": "Ecclésiaste 9:15–16", "soir_nouveau_testament": "Hebreux 2:1–18" },
  "day_288": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Jérémie 24–25", "midi_sagesse_poesie": "Lamentations 4:13–14", "soir_nouveau_testament": "Hebreux 3:1–19" },
  "day_289": { "jour_semaine": "Lundi", "matin_ancien_testament": "Jérémie 26–27", "midi_sagesse_poesie": "Psaume 118:16–29 ; Psaume 119:1–13", "soir_nouveau_testament": "Hebreux 4:1–16" },
  "day_290": { "jour_semaine": "Mardi", "matin_ancien_testament": "Jérémie 28–29", "midi_sagesse_poesie": "Proverbes 25:20–28", "soir_nouveau_testament": "Hebreux 5:1–14" },
  "day_291": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Jérémie 30–31", "midi_sagesse_poesie": "Ecclésiaste 9:17–18", "soir_nouveau_testament": "Hebreux 6:1–20" },
  "day_292": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Jérémie 32–33", "midi_sagesse_poesie": "Lamentations 4:15–16", "soir_nouveau_testament": "Hebreux 7:1–28" },
  "day_293": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Jérémie 34–35", "midi_sagesse_poesie": "Psaume 119:14–40", "soir_nouveau_testament": "Hebreux 8:1–13" },
  "day_294": { "jour_semaine": "Samedi", "matin_ancien_testament": "Jérémie 36–37", "midi_sagesse_poesie": "Proverbes 26:1–10", "soir_nouveau_testament": "Hebreux 9:1–28" },
  "day_295": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Jérémie 38–39", "midi_sagesse_poesie": "Ecclésiaste 10:1–3", "soir_nouveau_testament": "Hebreux 10:1–20" },
  "day_296": { "jour_semaine": "Lundi", "matin_ancien_testament": "Jérémie 40–41", "midi_sagesse_poesie": "Lamentations 4:17–18", "soir_nouveau_testament": "Hebreux 10:21–39" },
  "day_297": { "jour_semaine": "Mardi", "matin_ancien_testament": "Jérémie 42–43", "midi_sagesse_poesie": "Psaume 119:41–67", "soir_nouveau_testament": "Hebreux 11:1–20" },
  "day_298": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Jérémie 44–45", "midi_sagesse_poesie": "Proverbes 26:11–19", "soir_nouveau_testament": "Hebreux 11:21–40" },
  "day_299": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Jérémie 46–47", "midi_sagesse_poesie": "Ecclésiaste 10:4–6", "soir_nouveau_testament": "Hebreux 12:1–29" },
  "day_300": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Jérémie 48–49", "midi_sagesse_poesie": "Lamentations 4:19", "soir_nouveau_testament": "Hebreux 13:1–25" },
  "day_301": { "jour_semaine": "Samedi", "matin_ancien_testament": "Jérémie 50–51", "midi_sagesse_poesie": "Psaume 119:68–94", "soir_nouveau_testament": "1Thessaloniciens 1:1–10" },
  "day_302": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Jérémie 52 – Ézéchiel 1", "midi_sagesse_poesie": "Proverbes 26:20–28", "soir_nouveau_testament": "1Thessaloniciens 2:1–20" },
  "day_303": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ézéchiel 2–3", "midi_sagesse_poesie": "Ecclésiaste 10:7–9", "soir_nouveau_testament": "1Thessaloniciens 3:1–13" },
  "day_304": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ézéchiel 4–5", "midi_sagesse_poesie": "Lamentations 4:20", "soir_nouveau_testament": "1Thessaloniciens 4:1–18" },
  "day_305": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ézéchiel 6–7", "midi_sagesse_poesie": "Psaume 119:95–121", "soir_nouveau_testament": "1Thessaloniciens 5:1–28" },
  "day_306": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ézéchiel 8–9", "midi_sagesse_poesie": "Proverbes 27:1–9", "soir_nouveau_testament": "2Thessaloniciens 1:1–12" },
  "day_307": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ézéchiel 10–11", "midi_sagesse_poesie": "Ecclésiaste 10:10–12", "soir_nouveau_testament": "2Thessaloniciens 2:1–17" },
  "day_308": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ézéchiel 12–13", "midi_sagesse_poesie": "Lamentations 4:21", "soir_nouveau_testament": "2Thessaloniciens 3:1–18" },
  "day_309": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ézéchiel 14–15", "midi_sagesse_poesie": "Psaume 119:122–148", "soir_nouveau_testament": "1Timothee 1:1–20" },
  "day_310": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ézéchiel 16–17", "midi_sagesse_poesie": "Proverbes 27:10–18", "soir_nouveau_testament": "1Timothee 2:1–15" },
  "day_311": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ézéchiel 18–19", "midi_sagesse_poesie": "Ecclésiaste 10:13–14", "soir_nouveau_testament": "1Timothee 3:1–16" },
  "day_312": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ézéchiel 20–21", "midi_sagesse_poesie": "Lamentations 4:22", "soir_nouveau_testament": "1Timothee 4:1–16" },
  "day_313": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ézéchiel 22–23", "midi_sagesse_poesie": "Psaume 119:149–175", "soir_nouveau_testament": "1Timothee 5:1–25" },
  "day_314": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ézéchiel 24–25", "midi_sagesse_poesie": "Proverbes 27:19–27", "soir_nouveau_testament": "1Timothee 6:1–21" },
  "day_315": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ézéchiel 26–27", "midi_sagesse_poesie": "Ecclésiaste 10:15–16", "soir_nouveau_testament": "2Timothee 1:1–18" },
  "day_316": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ézéchiel 28–29", "midi_sagesse_poesie": "Lamentations 5:1–2", "soir_nouveau_testament": "2Timothee 2:1–26" },
  "day_317": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ézéchiel 30–31", "midi_sagesse_poesie": "Psaume 119:176 ; Psaume 120:1–7 ; Psaume 121:1–8 ; Psaume 122:1–9 ; Psaume 123:1–2", "soir_nouveau_testament": "2Timothee 3:1–17" },
  "day_318": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ézéchiel 32–33", "midi_sagesse_poesie": "Proverbes 28:1–10", "soir_nouveau_testament": "2Timothee 4:1–22" },
  "day_319": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ézéchiel 34–35", "midi_sagesse_poesie": "Ecclésiaste 10:17–18", "soir_nouveau_testament": "Tite 1:1–16" },
  "day_320": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Ézéchiel 36–37", "midi_sagesse_poesie": "Lamentations 5:3–4", "soir_nouveau_testament": "Tite 2:1–15" },
  "day_321": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Ézéchiel 38–39", "midi_sagesse_poesie": "Psaume 123:3–4 ; Psaume 124:1–8 ; Psaume 125:1–5 ; Psaume 126:1–6 ; Psaume 127:1–5 ; Psaume 128:1", "soir_nouveau_testament": "Tite 3:1–15" },
  "day_322": { "jour_semaine": "Samedi", "matin_ancien_testament": "Ézéchiel 40–41", "midi_sagesse_poesie": "Proverbes 28:11–19", "soir_nouveau_testament": "Philemon 1:1–25" },
  "day_323": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Ézéchiel 42–43", "midi_sagesse_poesie": "Ecclésiaste 10:19–20", "soir_nouveau_testament": "Jacques 1:1–27" },
  "day_324": { "jour_semaine": "Lundi", "matin_ancien_testament": "Ézéchiel 44–45", "midi_sagesse_poesie": "Lamentations 5:5–6", "soir_nouveau_testament": "Jacques 2:1–26" },
  "day_325": { "jour_semaine": "Mardi", "matin_ancien_testament": "Ézéchiel 46–47", "midi_sagesse_poesie": "Psaume 128:2–6 ; Psaume 129:1–8 ; Psaume 130:1–8 ; Psaume 131:1–3 ; Psaume 132:1–3", "soir_nouveau_testament": "Jacques 3:1–18" },
  "day_326": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Ézéchiel 48 – Daniel 1", "midi_sagesse_poesie": "Proverbes 28:20–28", "soir_nouveau_testament": "Jacques 4:1–17" },
  "day_327": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Daniel 2–3", "midi_sagesse_poesie": "Ecclésiaste 11:1–3", "soir_nouveau_testament": "Jacques 5:1–20" },
  "day_328": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Daniel 4–5", "midi_sagesse_poesie": "Lamentations 5:7–8", "soir_nouveau_testament": "1Pierre 1:1–25" },
  "day_329": { "jour_semaine": "Samedi", "matin_ancien_testament": "Daniel 6–7", "midi_sagesse_poesie": "Psaume 132:4–18 ; Psaume 133:1–3 ; Psaume 134:1–3 ; Psaume 135:1–6", "soir_nouveau_testament": "1Pierre 2:1–25" },
  "day_330": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Daniel 8–9", "midi_sagesse_poesie": "Proverbes 29:1–9", "soir_nouveau_testament": "1Pierre 3:1–22" },
  "day_331": { "jour_semaine": "Lundi", "matin_ancien_testament": "Daniel 10–11", "midi_sagesse_poesie": "Ecclésiaste 11:4–6", "soir_nouveau_testament": "1Pierre 4:1–19" },
  "day_332": { "jour_semaine": "Mardi", "matin_ancien_testament": "Daniel 12 – Osée 1", "midi_sagesse_poesie": "Lamentations 5:9–10", "soir_nouveau_testament": "1Pierre 5:1–14" },
  "day_333": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Osée 2–3", "midi_sagesse_poesie": "Psaume 135:7–21 ; Psaume 136:1–12", "soir_nouveau_testament": "2Pierre 1:1–21" },
  "day_334": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Osée 4–5", "midi_sagesse_poesie": "Proverbes 29:10–18", "soir_nouveau_testament": "2Pierre 2:1–22" },
  "day_335": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Osée 6–7", "midi_sagesse_poesie": "Ecclésiaste 11:7–8", "soir_nouveau_testament": "2Pierre 3:1–18" },
  "day_336": { "jour_semaine": "Samedi", "matin_ancien_testament": "Osée 8–9", "midi_sagesse_poesie": "Lamentations 5:11–12", "soir_nouveau_testament": "1Jean 1:1–10" },
  "day_337": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Osée 10–11", "midi_sagesse_poesie": "Psaume 136:13–26 ; Psaume 137:1–9 ; Psaume 138:1–4", "soir_nouveau_testament": "1Jean 2:1–29" },
  "day_338": { "jour_semaine": "Lundi", "matin_ancien_testament": "Osée 12–13", "midi_sagesse_poesie": "Proverbes 29:19–27", "soir_nouveau_testament": "1Jean 3:1–24" },
  "day_339": { "jour_semaine": "Mardi", "matin_ancien_testament": "Osée 14 – Joël 1", "midi_sagesse_poesie": "Ecclésiaste 11:9–10", "soir_nouveau_testament": "1Jean 4:1–21" },
  "day_340": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Joël 2–3", "midi_sagesse_poesie": "Lamentations 5:13–14", "soir_nouveau_testament": "1Jean 5:1–21" },
  "day_341": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Amos 1–2", "midi_sagesse_poesie": "Psaume 138:5–8 ; Psaume 139:1–23", "soir_nouveau_testament": "2Jean 1:1–13" },
  "day_342": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Amos 3–4", "midi_sagesse_poesie": "Proverbes 30:1–11", "soir_nouveau_testament": "3Jean 1:1–15" },
  "day_343": { "jour_semaine": "Samedi", "matin_ancien_testament": "Amos 5–6", "midi_sagesse_poesie": "Ecclésiaste 12:1–3", "soir_nouveau_testament": "Jude 1:1–25" },
  "day_344": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Amos 7–8", "midi_sagesse_poesie": "Lamentations 5:15–16", "soir_nouveau_testament": "Apocalypse 1:1–20" },
  "day_345": { "jour_semaine": "Lundi", "matin_ancien_testament": "Amos 9 – Abdias 1", "midi_sagesse_poesie": "Psaume 139:24 ; Psaume 140:1–13 ; Psaume 141:1–10 ; Psaume 142:1–3", "soir_nouveau_testament": "Apocalypse 2:1–29" },
  "day_346": { "jour_semaine": "Mardi", "matin_ancien_testament": "Jonas 1–2", "midi_sagesse_poesie": "Proverbes 30:12–22", "soir_nouveau_testament": "Apocalypse 3:1–22" },
  "day_347": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Jonas 3–4", "midi_sagesse_poesie": "Ecclésiaste 12:4–6", "soir_nouveau_testament": "Apocalypse 4:1–11" },
  "day_348": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Michée 1–2", "midi_sagesse_poesie": "Lamentations 5:17–18", "soir_nouveau_testament": "Apocalypse 5:1–14" },
  "day_349": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Michée 3–4", "midi_sagesse_poesie": "Psaume 142:4–7 ; Psaume 143:1–12 ; Psaume 144:1–11", "soir_nouveau_testament": "Apocalypse 6:1–17" },
  "day_350": { "jour_semaine": "Samedi", "matin_ancien_testament": "Michée 5–6", "midi_sagesse_poesie": "Proverbes 30:23–33", "soir_nouveau_testament": "Apocalypse 7:1–17" },
  "day_351": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Michée 7 – Nahum 1", "midi_sagesse_poesie": "Ecclésiaste 12:7–8", "soir_nouveau_testament": "Apocalypse 8:1–13" },
  "day_352": { "jour_semaine": "Lundi", "matin_ancien_testament": "Nahum 2–3", "midi_sagesse_poesie": "Lamentations 5:19", "soir_nouveau_testament": "Apocalypse 9:1–21" },
  "day_353": { "jour_semaine": "Mardi", "matin_ancien_testament": "Habacuc 1–2", "midi_sagesse_poesie": "Psaume 144:12–15 ; Psaume 145:1–21 ; Psaume 146:1–2", "soir_nouveau_testament": "Apocalypse 10:1–11" },
  "day_354": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Habacuc 3 – Sophonie 1", "midi_sagesse_poesie": "Proverbes 31:1–11", "soir_nouveau_testament": "Apocalypse 11:1–19" },
  "day_355": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Sophonie 2–3", "midi_sagesse_poesie": "Ecclésiaste 12:9–10", "soir_nouveau_testament": "Apocalypse 12:1–18" },
  "day_356": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Aggée 1–2", "midi_sagesse_poesie": "Lamentations 5:20", "soir_nouveau_testament": "Apocalypse 13:1–18" },
  "day_357": { "jour_semaine": "Samedi", "matin_ancien_testament": "Zacharie 1–2", "midi_sagesse_poesie": "Psaume 146:3–10 ; Psaume 147:1–19", "soir_nouveau_testament": "Apocalypse 14:1–20" },
  "day_358": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Zacharie 3–4", "midi_sagesse_poesie": "Proverbes 31:12–21", "soir_nouveau_testament": "Apocalypse 15:1–8" },
  "day_359": { "jour_semaine": "Lundi", "matin_ancien_testament": "Zacharie 5–6", "midi_sagesse_poesie": "Ecclésiaste 12:11–12", "soir_nouveau_testament": "Apocalypse 16:1–21" },
  "day_360": { "jour_semaine": "Mardi", "matin_ancien_testament": "Zacharie 7–8", "midi_sagesse_poesie": "Lamentations 5:21", "soir_nouveau_testament": "Apocalypse 17:1–18" },
  "day_361": { "jour_semaine": "Mercredi", "matin_ancien_testament": "Zacharie 9–10", "midi_sagesse_poesie": "Psaume 147:20 ; Psaume 148:1–14 ; Psaume 149:1–9 ; Psaume 150:1–3", "soir_nouveau_testament": "Apocalypse 18:1–24" },
  "day_362": { "jour_semaine": "Jeudi", "matin_ancien_testament": "Zacharie 11–12", "midi_sagesse_poesie": "Proverbes 31:22–31", "soir_nouveau_testament": "Apocalypse 19:1–21" },
  "day_363": { "jour_semaine": "Vendredi", "matin_ancien_testament": "Zacharie 13–14", "midi_sagesse_poesie": "Ecclésiaste 12:13–14", "soir_nouveau_testament": "Apocalypse 20:1–15" },
  "day_364": { "jour_semaine": "Samedi", "matin_ancien_testament": "Malachie 1–2", "midi_sagesse_poesie": "Lamentations 5:22", "soir_nouveau_testament": "Apocalypse 21:1–27" },
  "day_365": { "jour_semaine": "Dimanche", "matin_ancien_testament": "Malachie 3–4", "midi_sagesse_poesie": "Psaume 150:4–6", "soir_nouveau_testament": "Apocalypse 22:1–21" }
};